version: "3.7"
services:
  server:
    build: .
    restart: always
    ports:
      - 8081:8082
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: "mysql:8.0.29"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: fashion_Blog
      MYSQL_ROOT_PASSWORD: Agirllikeme04
      MYSQL_ROOT_USERNAME: root